---
   environment: development
   chdir: /Users/ross/projects/heuristics/server
   address: 127.0.0.1
   port: 4567
   pid: /Users/ross/projects/heuristics/server/tmp/thin.pid
   rackup: /Users/ross/projects/heuristics/server/thin/config.ru
   log: /Users/ross/projects/heuristics/server/log/thin.log
   max_conns: 1024
   timeout: 30
   max_persistent_conns: 512
   daemonize: true